name:                case01
version:             0.1.0.0
github:              "waddlaw/case01"
license:             BSD3
author:              "Shinya Yamaguchi"
maintainer:          "ingroze@gmail.com"
copyright:           "Copyright (c) 2018 Shinya Yamaguchi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Your Projects Category

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/waddlaw/case01#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  case1:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - case01